### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by AIGeneratedUsername** [florimondmanca/msgpack-asgi#13] opened 2021-07-23 14:47 UTC
1. Why it does not support HTTPS?
2. How to make it working with HTTPS?

```python
class MessagePackMiddleware:
    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] == "http":
            responder = _MessagePackResponder(self.app)
            await responder(scope, receive, send)
            return
        await self.app(scope, receive, send)
```

**Comment by florimondmanca** [comment] 2021-07-23 17:37
Hi @AIGeneratedUsername,

How does it _not_ work with HTTPS? The `scope["type"] == "http"` is an ASGI detail — that code path is followed for HTTP(S) requests, as opposed to WebSocket requests. HTTPS requests _should_ be supported, since HTTPS data is decoded by the server and sent to ASGI apps transparently when they call `receive()`.

Closing since I think this is a misunderstanding, but if there's really something wrong, could you provide a minimal working reproduction case? Thanks.

**Closed by florimondmanca** 2021-07-23 17:37 UTC
